services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: database_optimization
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  # api:
  #   build: .
  #   environment:
  #     POSTGRES_HOST: postgres
  #     POSTGRES_PORT: 5432
  #     POSTGRES_DB: databse_optimization
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - '8000:8000'
  #   depends_on:
  #     - postgres

volumes:
  postgres-data:
