[project]
name = "api-optimization"
version = "0.1.0"
description = "A simple asynchronous FastAPI and PostgreSQL baseline for database performance experiments."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "cashews>=7.5.0",
    "email-validator>=2.2.0",
    "faker>=28.0.0",
    "fastapi>=0.115.0",
    "httpx>=0.27.0",
    "opentelemetry-distro>=0.65b0",
    "opentelemetry-exporter-otlp>=1.44.0",
    "opentelemetry-instrumentation-asyncio==0.65b0",
    "opentelemetry-instrumentation-click==0.65b0",
    "opentelemetry-instrumentation-dbapi==0.65b0",
    "opentelemetry-instrumentation-exceptions==0.65b0",
    "opentelemetry-instrumentation-fastapi==0.65b0",
    "opentelemetry-instrumentation-grpc==0.65b0",
    "opentelemetry-instrumentation-httpx==0.65b0",
    "opentelemetry-instrumentation-logging==0.65b0",
    "opentelemetry-instrumentation-psycopg==0.65b0",
    "opentelemetry-instrumentation-requests==0.65b0",
    "opentelemetry-instrumentation-sqlite3==0.65b0",
    "opentelemetry-instrumentation-starlette==0.65b0",
    "opentelemetry-instrumentation-threading==0.65b0",
    "opentelemetry-instrumentation-tortoiseorm==0.65b0",
    "opentelemetry-instrumentation-urllib==0.65b0",
    "opentelemetry-instrumentation-urllib3==0.65b0",
    "opentelemetry-instrumentation-wsgi==0.65b0",
    "psycopg-pool>=3.3.1",
    "psycopg[binary]>=3.2.0",
    "pydantic>=2.8.0",
    "pytest>=8.3.0",
    "pytest-asyncio>=0.24.0",
    "redis>=8.1.0",
    "slowapi>=0.1.10",
    "uvicorn[standard]>=0.30.0",
]

[project.scripts]
dev = " app.main:run"
seed = "scripts.seed:run"
test = "pytest:main"
client = "scripts.client:run"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
package = true

[tool.hatch.build.targets.wheel]
packages = ["app", "scripts"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
